name: Outrun
favicon: null
layout_spectrum: 0.24564
typography_spectrum: 0.2228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1cb9c8'
    - '#ffffff'
    - '#222222'
    - '#bababa'
    - '#5b5b5b'
  brandStrength: 1
  lightness: 0.7430094173178077
  saturation: 0.9726098931860179
  rhythmicContrast: 0.43951692688278854
purpose: []
